[package]
name = "libp2p-webrtc"
version = "0.1.0-alpha"
authors = ["Parity Technologies <admin@parity.io>"]
description = "WebRTC transport for libp2p"
repository = "https://github.com/libp2p/rust-libp2p"
license = "MIT"
edition = "2021"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-trait = "0.1"
asynchronous-codec = "0.6.1"
bytes = "1"
futures = "0.3"
futures-timer = "3"
hex = "0.4"
hkdf = "0.12.3"
if-watch = "2.0"
libp2p-core = { version = "0.38.0", path = "../../core"  }
libp2p-noise = { version = "0.41.0", path = "../../transports/noise" }
log = "0.4"
multihash = { version = "0.16", default-features = false, features = ["sha2"] }
pem = "1.1.0"
prost = "0.11"
prost-codec = { version = "0.3.0", path = "../../misc/prost-codec" }
rand = "0.8"
rand_chacha = "0.3.1"
ring = { git = "https://github.com/briansmith/ring", features = ["std"], rev = "abe9529fc063f575759f8166bba02db171a3a0f6" }
rustls = "0.19.1" # Must match version in webrtc library.
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.6"
simple_x509 = "=0.2.2" # Version MUST be pinned to ensure a patch-update doesn't accidentially break deterministic certs.
stun = "0.4"
thiserror = "1"
tinytemplate = "1.2"
tokio = { version = "1.18", features = ["net"], optional = true}
tokio-util = { version = "0.7", features = ["compat"], optional = true }
# webrtc = { version = "0.5.0", optional = true }
webrtc = { git = "https://github.com/thomaseizinger/webrtc", optional = true, rev = "dc8d896784eb7ba8f5cecc2e5ae2917bb16c0c65" }

[features]
tokio = ["dep:tokio", "dep:tokio-util", "dep:webrtc"]

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
anyhow = "1.0"
env_logger = "0.9"
hex-literal = "0.3"
libp2p = { path = "../..", features = ["request-response", "webrtc", "ping"], default-features = false }
tokio = { version = "1.18", features = ["full"] }
unsigned-varint = { version = "0.7", features = ["asynchronous_codec"] }
rand_chacha = "0.3.1"

[[test]]
name = "smoke"
required-features = ["tokio"]

[[example]]
name = "listen_ping"
required-features = ["tokio"]
